import type { Metadata } from "next";
import { Open_Sans, Courier_Prime } from "next/font/google";
import "./globals.css";

const OpenSans = Open_Sans({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={`${OpenSans.className} bg-zinc-800`}>{children}</body>
    </html>
  );
}
